name: Deploy to EasyPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EasyPanel via Webhook
        run: |
          curl -X POST "${{ secrets.EASYPANEL_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d '{
              "ref": "refs/heads/main",
              "repository": {
                "full_name": "${{ github.repository }}"
              }
            }'
        env:
          EASYPANEL_WEBHOOK_URL: ${{ secrets.EASYPANEL_WEBHOOK_URL }}

      - name: Wait for deployment
        run: sleep 30

      - name: Notify success
        run: echo "✅ Deployment triggered successfully!"
